### ISSUE TITLE
Create a master list of things to do / update for each release of each SDK

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#153]
Inside each SDK, we can have a file called `ON_RELEASE.md` which will contain a checklist of things to do for each release.
For example, when we release a new version of supertokens-node, then we need to update the docs version, the demo app, the nexjs app etc.. likewise when we need to release a new version of supertokens-auth-react, we need to update the docs, the demo app, the custom theme apps etc etc..

**Comment by NkxxkN** [comment]
Good idea!

Since we are going to want to create a new tracking issue each time we want to release a new feature, let's create an issue template such as https://github.com/supertokens/supertokens-core/blob/master/.github/ISSUE_TEMPLATE/bug.md
so that we can generate the issue automatically with all the checkbox ready.

I feel like we should think of it as a whole and not have one file per repository. 

Since, for example, when releasing email verification, `supertokens-auth-react` has to wait for `supertokens-node` repo to be released in order to update the version of `supertokens-node` in the tests.
NextJS demo app will need to wait for `supertokens-auth-react`, `supertokens-node` and for the core to be updated on `https://try.supertokens.io`. 

It will be easier to handle dependencies if everything lives in one issue.

It will also be easier to update if it's in one file only.
