### ISSUE TITLE
Sign in / up UI responsiveness issues

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#162]
- The UI is initially zoomed in on mobile
- There is no margin on the right and left of the widget
- There is left padding in the text input, but no right padding (this is true on desktop as well).
- https://github.com/supertokens/supertokens-auth-react/issues/43

**Comment by rishabhpoddar** [comment]
I have release auth-react 0.4.1. Please feel free to close this issue if it's fully done

**Comment by rishabhpoddar** [comment]
This is not fully done as issues like "There is left padding in the text input, but no right padding (this is true on desktop as well)." are still there.

**Comment by NkxxkN** [comment]
Good catch. I missed that one. Closing now.

**Comment by rishabhpoddar** [comment]
Reopening cause Mufassir has to make some more changes...

**Comment by rishabhpoddar** [comment]
If this issue is done, please close it

**Comment by rishabhpoddar** [comment]
Reopening since there are more changes.. @mufassirkazi please write your changes here.

**Comment by NkxxkN** [comment]
From conversation with Mufassir:

>  left padding is too much for the input field. In the design it is 15 px i guess, you have 20 px. Also, when I focus on the input field, that field color should change from that grey to white as done in the design. 
 
 Thought I would open a new issue since it will not be on 0.4.2 but on next release because it's minor changes (not worth an update on its own).

**Comment by rishabhpoddar** [comment]
We can keep this one open until that is done

**Comment by mufassirkazi** [comment]
- Left padding should be reduced from 20 px to 15 px
- In focus state, change the original background colour of the input field to 0.25% of the opacity
- Border radius should be 6px as opposed to 8px that we currently have for all input fields, buttons and the main white container itself
- When I load the page the UI is initially a little zoomed in on mobile.

**Comment by mufassirkazi** [comment]
The UI looks like this on initial load

![WhatsApp Image 2021-01-18 at 9 19 53 PM](https://user-images.githubusercontent.com/46087290/104936777-fbf3df80-59d2-11eb-94e7-389179ed7ae5.jpeg)

Ideally should look like this:

![WhatsApp Image 2021-01-18 at 9 16 53 PM](https://user-images.githubusercontent.com/46087290/104936880-204fbc00-59d3-11eb-8b5e-dfb6d5f5accc.jpeg)

**Comment by NkxxkN** [comment]
>Left padding should be reduced from 20 px to 15 px
In focus state, change the original background colour of the input field to 0.25% of the opacity
Border radius should be 6px as opposed to 8px that we currently have for all input fields, buttons and the main white container itself

Fixed in https://github.com/supertokens/supertokens-auth-react/pull/136

About focus state not being visible on Iphone SE, according to this [stackoverflow](https://stackoverflow.com/questions/30584335/css-focus-not-working-in-ios), it's a global issue, it can be solved by setting an obscure `ontouchstart` attr on the document body.

```js
<body ontouchstart="">
...
</body>
```

I've never seen this attribute before so I think that it's a widespread issue that you must be experiencing with quite a lot of website @mufassirkazi ? Can you try https://gitlab.com/users/sign_in on mobile and let me know if you get the focus state?

In any cases, it's an issue solvable by the website and not by the lib.

Same goes for the app being zoomed in. See https://stackoverflow.com/questions/10756949/why-do-mobile-browsers-load-my-page-completely-zoomed-in

**Comment by rishabhpoddar** [comment]
Please close this if it's done after the latest PR.
