### ISSUE TITLE
Reduce `supertokens-node` / `supertokens-auth-react` bundle size

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#178]
By trying to make our libs modular, we have made it heavy in import size.

![image](https://user-images.githubusercontent.com/5072452/106117961-de054800-6153-11eb-993c-30d63e33268d.png)

Because EmailPassword above has dependencies on `SuperTokens`, there is no point in separating the import of EmailPassword into a separate file.

With a basic install including email password and session, we are actually increasing the size by 3. 
Same goes for supertokens-node (500K to 217Ko gzipped).

Should we bring all recipe's to the main index file? 

-----------------------

In the final build it does not actually make any difference:
Import from recipe files:
![image](https://user-images.githubusercontent.com/5072452/106140066-8de7af00-616e-11eb-80c2-6d6b05f8a850.png)

Import from main file:

![image](https://user-images.githubusercontent.com/5072452/106140143-aa83e700-616e-11eb-99c3-fdfbf43bf054.png)

On the other hand, it seems that two libs are taking up to 80% of `supertokens-node`

https://bundlephobia.com/result?p=supertokens-node@3.3.1

![image](https://user-images.githubusercontent.com/5072452/106139684-0601a500-616e-11eb-88a5-83627d9c8ca6.png)

`mime-db` is imported from `express` and `iconv-lite` is imported from `body-parser`. Not much we can do as both are pretty important for the package. Or can we make those optional dependencies? Same way we do for `react-router-dom` in the front end package.

Not necessarily a problem now but since I was taking a look at it I wanted to make sure to take notes somewhere.

**Comment by nkshah2** [comment]
@porcellus I think a good idea would be to allows users to check the bundle size of our SDkKs outside of PRs as well. For example if I was evaluating using supertokens-auth-react I should be able to check what the bundle of of the SDK is. Today the only way to do that is going to NPMs website but that number is inaccurate because the actual bundle size would depend on which recipe(s) you are using.

Maybe we should have a link that displays the bundle size for each recipe, we could link this in the READMEs of each SDK so that people can check them out without relying on PR conversations. As a bonus if we could display the final output directly in our READMEs that would be great

**Comment by porcellus** [comment]
It's a great idea! However, the current solution isn't really suited for it: it includes dependencies like the react in the bundle size which is not realistic. It's more of a tool that we can use to compare between PRs. 
- I'll add a follow-up issue for this. 
- Another follow-up issue will be to try and reduce the size of the dependencies we use (about 1/3 of our pre-gzip size comes from 2-3 dependencies)

**Comment by rishabhpoddar** [comment]
As discussed, we don't need to worry about the axios part since it will cause a breaking change in the API and it's not that big
