### ISSUE TITLE
Magic links discussion

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#212]
- Design: https://github.com/supertokens/supertokens-core/issues/202
- Pricing of other services: https://github.com/supertokens/main-website/issues/456

**Comment by jscyo** [comment]
Devs expressing some points about why they dont like magic links [source](https://news.ycombinator.com/item?id=20453810)

Some of the major points in the thread:
- Inconvenient if using incognito/private window, friends computer, school PC’s dont have access to email. (Op favours using email password with a password manager app on his phone)
- An additional step in the ux process.(Op clarifies that it depends on how frequently he would have to log in, if he was logged in all the time its fine, but if he had to log in frequently it would get annoying)
  - This point is echoed a number of times in the thread
- Dev for a banking company mentions that when they implemented magic links, some of their users hated it. They said its slower than having a password and its a cumbersome second step.
- Constant flood emails everytime the user logs in.
- What happens when a users email gets compromised?

**Comment by rishabhpoddar** [comment]
https://medium.com/tresorit-engineering/how-we-designed-file-request-links-c5dd81c034b3

**Comment by glenarama** [comment]
Most objections I've seen to Magic links is when they are implemented to log into the link page/tab rather than the origin tab.
i.e: Someone clicks login on their browser, clicks the login link on their phone and are now logged in on their phone, not where they wanted to be. Magic.link implements this more elegantly - login in on the original tab, regardless of where you authenticate the email link.

This also avoids the issue above:
- Inconvenient if using incognito/private window

What is the proposed workflow for this solution?

**Comment by rishabhpoddar** [comment]
@glenarama isn't logging into the original tab a security issue?
- Attacker clicks on login on his computer.
- Unaware user receives an email and clicks on the link in the email (by mistake).
- Attacker is now logged in.

**Comment by glenarama** [comment]
I think thats a fair concern.

magic.link & Vercel.com both use this approach so obviously feel it's an acceptable risk.
Both make it very clear on the email that you requested a login and have a relatively short expiration.
The UX is far better IMO, a magic link system logging into the email browser feels broken to me and loses the appeal of password-less. Im sure highly security minded folk would feel quite strongly the other way.

The concern I have with the above suggestion is:
1. It adds yet another step to the login flow given the comment:  "An additional step in the ux process."
2. If a user is happy to click a link in the email, is clicking a link on the landing page any different/safer?

**Comment by rishabhpoddar** [comment]
> It adds yet another step to the login flow given the comment: "An additional step in the ux process."

Fair enough. Perhaps we can make it so that it's configurable to switch that on or off.

> If a user is happy to click a link in the email, is clicking a link on the landing page any different/safer?

What do you mean by "clicking on the landing page"?

**Comment by glenarama** [comment]
> > If a user is happy to click a link in the email, is clicking a link on the landing page any different/safer?
> 
> What do you mean by "clicking on the landing page"?

If the user isn't paying attention and clicks on the email link - they could also not pay attention and click on the "login to original browser" I mean there is still a security risk there, even if it's one step removed.

**Comment by rishabhpoddar** [comment]
> they could also not pay attention and click on the "login to original browser"

yea true.. however, it's still an added step - reduces the probability.

> I personally think most of the negative feedback on magic links come from this issue.

Agreed. That's why we want to provide a balance between UX and security.. it's debatable and tricky for sure.

**Comment by rishabhpoddar** [comment]
Closing in preference to https://github.com/supertokens/for-zenhub/issues/63
