### ISSUE TITLE
Merge social accounts with same email

### ISSUE THREAD

**Issue by olhapi** [supertokens/supertokens-core#249]
## 🚀 Feature

Now if there's an email/password registered account and user want to login through some social account -> new account would be created for each social login. 

## Implementation details

I think it would be great to merge social accounts by email and not create duplicates.

**Comment by rishabhpoddar** [comment]
@olhapi thanks for this issue. We explicitly didn't add this feature, since this adds security risk:
- Let's say you offer sign in with ProviderX (pX) and ProviderY (pY)
- A user has the same email on both pX and pY
- An attacker has somehow gained access to user's pX account.
- The user previously created an account on your app using sign in with pY.
- Now the attacker can gain access to the user's account on your app by signing in with pX (since she controls pX).

We also realise there is a UX issue where users might forget which provider they used to sign in and end up creating duplicate accounts unnecessarily.

To solve this, whilst maintaining security, we plan on reminding users which account they had previously used to create an account. They can then choose to login with that option, or continue to create a new account.

Related to: https://github.com/supertokens/supertokens-core/issues/182#issuecomment-824161301

**Comment by olhapi** [comment]
@rishabhpoddar totally makes sense, I've never thought about that, thx for pointing out 🤔

I think there's need in reminder when user with already registered email adding another social account, just as you said. With that feature will be no need in merging accounts (especially if that's security flaw).
