### ISSUE TITLE
Implement a way for open source users to know if there are security or bug fixes

### ISSUE THREAD

**Issue by makerboiAdi** [supertokens/supertokens-core#26]
This would involve open source developers to optionally share their details and the version they use so that incase of critical issues, we can inform them that they should update the version of the SuperTokens Core

**Comment by rishabhpoddar** [comment]
Initial thoughts:
- See [mattermost telemetry](https://docs.mattermost.com/administration/telemetry.html)
- When signing up on the app / user management dashboard, send that email ID to our servers with the consent of the user. This email would get a notification in case of security updates
- Have an option to disable this completely in order to disable all communication with our servers. In case this is done, send a final "goodbye" ping to our servers.
- The functioning of the binary should not be affected by the uptime of our servers

----------
Discussion points:
- [ ] Do we need to send a "ping" to our servers from a running binary on a continuous basis? Or just once initially, until we get the email ID to notify?

**Comment by NkxxkN** [comment]
Since SuperTokens is downloaded after signing up, we can keep track of which version was downloaded for an appId. Then, when the user uses `supertokens update --core`, we can send the appId alongside the downloading request to update the the known version for this application.
This would be optional as mentioned in previous comments.

That way we do not need to ping our servers occasionally from the core, only when the version is updated.

**Comment by rishabhpoddar** [comment]
From a development point of view, it's still very useful to know which versions of SuperTokens are being used. This way, we can depreciate older versions safely. To do this initially, we can generate a random UUID for an installation and use that to identify that installation and its version. This way, we won't know who that user is, but we will know that someone is using a certain version.

Once we have a dashboard where users have to sign up, then we can use that to notify them when necessary.

We will provide a way to disable this functionality.

**Comment by rishabhpoddar** [comment]
@NkxxkN please implement the anonymous method of send info. I believe that this should not require any changes to the plugins.

**Comment by rishabhpoddar** [comment]
For this API, we can take as an input:
- SuperTokens version (X.Y.Z)
- App Name, Website domain

@bhumilsarvaiya please create an API in `POST https://api.supertokens.io/0/st/ping`

**Comment by bhumilsarvaiya** [comment]
**API Endpoint**: `/0/st/ping`
**Method**: `PUT`
**Success Response**: `{}`
**Success Response Code**: `200`
**Possible Response Codes**: `200, 400, 408, 500`
**Required in Request**:
- headers:
    - api-version: 0
- request-body:
   ```
   {
       websiteDomain: string,
       appName: string,
       version: string  // X.Y.Z
   }
   ```
