### ISSUE TITLE
Add Delete User API in EmailPassword and ThirdParty recipes

### ISSUE THREAD

**Issue by dulowski-marek** [supertokens/supertokens-core#273]
### Goal
Developer should be able to delete a user's account.

### Problems and assumptions
1. User's account can be deleted either by user themselves or by someone else having necessary permissions (an admin). I think that we shouldn't differentiate the API, so that we have one endpoint `DELETE /users/{id}`. `id` parameter would be used to determine which user is being deleted. The permission would be extracted from `Authorization` permissions. At this moment let's specify that **user has the permission to delete himself**.
2. User should not be able to make further requests, so all his sessions have to be revoked. Revocation means, that issued access tokens cannot be used to interact with protected APIs, so this is directly bound to access token validation.

    - Does the validation happen in backend SDK or core? 
    - Does type of access token (JWT/opaque) play a role in validation?

    The main concern is that issuing access tokens as JWTs introduces distributed session state we have to change when deleting a user. (JWTs can be validated just with JWKS without pinging the core, which is one of their primary advantages).

3. Sessions need to be revoked first to maintain data consistency (session cannot reference a user that doesn't exist).
4. Client should not make request to core directly. Instead, the request should be done to backend SDK to maintain the FDI/CDI interfaces architecture. This means, that it's the backend SDK that will receive original `Authorization` header. If the deletion happens in core, it's the core however that will be validating the permissions to execute this action.
    - How does the backend SDK authorize requests to core?

### Subtasks
- [ ] Add Delete User in EmailPassword
- [ ] Add Delete User in ThirdParty

**Comment by rishabhpoddar** [comment]
> so that we have one endpoint DELETE /users/{id}

This API needs to go in the CDI spec. You should modify the swagger spec (v2.8.0) to add this API endpoint. Also, we don't really follow the `/{id}` style in any other API. So please make this API spec similar to how other APIs are. For example, I had already added this API: https://github.com/supertokens/core-driver-interface/blob/master/v2.8.0.md#recipeuser-delete

> The permission would be extracted from Authorization permissions.

There is no concept of permissions.. the API is exposed via the core, and it can be called by anything having access to the core. If an API key is set in the core, it needs to be supplied (again, see API spec in the link above).

> User should not be able to make further requests, so all his sessions have to be revoked

We should revoke all sessions of a user in the core. This will remove all their `sessionHandle` and the refresh tokens. This means the next time their session needs refreshing, they will be logged out.

Session revocation must also happen at the SDK level since our users may override how sessions work. This is tricky since we need to think about where it will happen. Should:
1) EmailPassword recipe exposes a `deleteUser` recipe function which will first revoke all sessions belonging to that user and then delete the user? Or
2) Should that function only call the core to delete a user which then deletes the sessions at the core level?

With (1), even if a dev overrides the session recipe, the sessions they create will be deleted (as expected), but we are violating a recipe design principle (see [this](https://github.com/supertokens/supertokens-core/wiki/Recipe-development-guideline-for-the-backend-and-frontend-recipes), and search for "Recipe functions should be as isolated as possible.. ") in which one a recipe function is calling other recipes (which it should not?). With (2), we are not violating the recipe design principle, but the in dev overrides the session recipe, then their sessions will still continue to exist...

> Does the validation happen in backend SDK or core?

In the backend SDK if blacklisting is not enabled. Otherwise it happens in the core.

> Does type of access token (JWT/opaque) play a role in validation?

There is only one type of access token..

> The main concern is that issuing access tokens as JWTs introduces distributed session state we have to change when deleting a user.

This is OK. People can work around it by using the access token blacklisting feature.

> Sessions need to be revoked first to maintain data consistency (session cannot reference a user that doesn't exist).

Agreed. That being said, sessions are a totally different recipe. And while refreshing a session, there is no logic done there that checks if the associated user actually exists or not.

> Client should not make request to core directly. Instead, the request should be done to backend SDK to maintain the FDI/CDI interfaces architecture. 

This is how our architecture is designed. It doesn't really need to be stated. But OK.

> This means, that it's the backend SDK that will receive original Authorization header.

We don't have a concept of "Authorization header". One more point to clarify, I don't think we should expose a delete user API via the FDI spec. This is because application developers may not want the frontend client to be able to call any such API, and us exposing it by default may result in unintended concequences. Therefore, it should only be a CDI change. If someone wants to make a delete user API and expose it to the frontend, then can do so by creating their own API using the recipe functions we have.

> If the deletion happens in core, it's the core however that will be validating the permissions to execute this action.

The only concept of permissions is an API key. We don't have roles...

**Comment by dulowski-marek** [comment]
> There is no concept of permissions.. the API is exposed via the core, and it can be called by anything having access to the core. If an API key is set in the core, it needs to be supplied (again, see API spec in the link above).

Then, does the API key have assigned permissions in any way?

I think this is a flaw of current design.
Imagine a common scenario where a developer creates some application using supertokens. He wants to expose an API to allow user to delete their account or allow superuser to delete some user account. To differentiate between those, you need to have some concept of permissions. Let's assume user has to come up with his own permissions system, because we don't provide that (assume `users.delete` and `users.delete_self`). In OAuth flows this is expressed as scopes, which are then accessible in a JWT payload.

But the information contained in original request is lost, because we use API key that either allows everything or nothing. This lack of granularity is a bad practice, as there might be several client SDKs that require different level of access (think admin API server, user self-service server, several services requiring only token verification). Those API keys are long-lived. If such API key is compromised, access to all APIs is granted, which maximizes the impact of such incident.

I think this is a part of our business logic and we should be able to handle permissions in core: either by passing original authorization grant or by having them assigned to the API key.

> 1) EmailPassword recipe exposes a deleteUser recipe function which will first revoke all sessions belonging to that user and then delete the user? Or
> 2) Should that function only call the core to delete a user which then deletes the sessions at the core level?
> 
> With (1), even if a dev overrides the session recipe, the sessions they create will be deleted (as expected), but we are violating a recipe design principle (see this, and search for "Recipe functions should be as isolated as possible.. ") in which one a recipe function is calling other recipes (which it should not?). With (2), we are not violating the recipe design principle, but the in dev overrides the session recipe, then their sessions will still continue to exist...

I don't see this problem with (1). Primarily because I think that Session doesn't quite fit the notion of a recipe, as other recipes produce sessions as their "outputs" on successful sign in. What is the goal of a dev in overriding the session mechanism? Do you have a specific usecase in mind?

> There is only one type of access token..

Even if we currently support JWTs only, I'm trying to think how the system may evolve in the future to not introduce implementation/breaking change problems down the road.

> Agreed. That being said, sessions are a totally different recipe. And while refreshing a session, there is no logic done there that checks if the associated user actually exists or not.

So we should also be able to blacklist refresh tokens associated with given user.

> We don't have a concept of "Authorization header".

I spoke about `Authorization` header just to state some method of frontend request authorization in backend that uses our SDK. It can be any authorization grant.

> If someone wants to make a delete user API and expose it to the frontend, then can do so by creating their own API using the recipe functions we have.

Exactly this introduces the permission problem I'm talking about. How are they going to tell the users apart? Even with their own permissions system in place, we should be able to verify that in core, because core is the target of the request that executes the business logic.

**Comment by rishabhpoddar** [comment]
> So we should also be able to blacklist refresh tokens associated with given user.

That happens automatically when the session is revoked from the table.

> Exactly this introduces the permission problem I'm talking about. How are they going to tell the users apart? Even with their own permissions system in place, we should be able to verify that in core, because core is the target of the request that executes the business logic.

I don't quite understand this. Perhaps we can discuss this over a call if this is still relevant.

**Comment by rishabhpoddar** [comment]
One important point: When delete a user from the core, we need to delete the sessions and the user in a transactional manner so that there is no new session created right after we "think" we have deleted all the sessions and before deleting the user.

**Comment by rishabhpoddar** [comment]
We also need to plan docs for this. In the context of all recipes, including sessions.

**Comment by rishabhpoddar** [comment]
Closing in favour of: https://github.com/supertokens/supertokens-core/issues/341
