### ISSUE TITLE
Core API logic pseudo code for passwordless

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-core#322]
Core API logic pseudo code for passwordless

**Comment by rishabhpoddar** [comment]
@porcellus the CDI and FDI spec need to be updated.

**Comment by rishabhpoddar** [comment]
# Feedback

## https://app.code2flow.com/OFxcbh1FNLXd (POST /recipe/sigininup/code/consume)
- [ ] After we successfully get a lock on line 36, shouldn't we then check if the device exists and the linkCode exists? I guess my point here is that we should try and get a lock on the device_id_hash on the passwordless_devices table as soon as possible. That would be before we check if the code has expired etc.. So the flow would be:
   - If linkCode is passed, we fetch the device_id_hash based on that
   - If device_id is passed, we hash it to get he device_id
   - Now that we have the device_id, we lock it (so in the diagram, there should only be one box for locking)
   - Post the above, check if the device still exists and for code matching / expiry etc...
   - If there is a deadlock, we go back to the step of locking with this device_id.
- [ ] There is a comment that is incomplete "No need to lock, because"
- [ ] Should we let line 75 happen via the cronjob instead of doing it here? Instead here, when we consume a code, we check if it's already exceeded the failed attempts and if it has, we send a restart flow error. I say this cause:
   - If a user changes (by reducing) the config for max number of failed attempts, then there could be existing rows in the db that were invalid before, but now they won't be. So there has to be something that removes them (the cronjob), and this API will have to take this scenario into account.
- [ ] line 61 -> can you explain why in the diagram?

## https://app.code2flow.com/MnqlXSzyjajO (cronjob)
- [ ] "get and lock all expired codes" -> shouldn't we actually be locking on device_id_hash? So this would be get all expired codes' device_ids. Then for each one, we loop through and lock that device_id_hash, and delete its expired code along with the device itself if there are no codes left.
- [ ] Also, this needs to take into account max number of failed attempts being passed (as per my comment above)

**Comment by porcellus** [comment]
> After we successfully get a lock on line 36, shouldn't we then check if the device exists and the `linkCode` exists?

- We should check if the device exists (I kinda forgot I always did that explicitly after each get).
- In user code input flow the device is locked before all of this.
- Checking the code expiration before locking the device doesn't take any time and we save 1 lock if someone keeps clicking on an expired link (if we are doing it in separate queries, we could actually select, lock and check the expiration in a single one)
  - The downside to this is if the code expires while another transaction locked the device.

> If there is a deadlock, we go back to the step of locking with this device_id.

I think the deadlock error should just restart the transaction in the current implementation. 
We could add extra code to handle this, but it should be rare anyway and work the same way.

> Should we let line 75 happen via the cronjob instead of doing it here?

We could do it there as well, but I assumed that they would be cleaned up the next time they were used or when they expired, but this is something we could add easily.
The advantage of doing it during consume is that it can shortcut a bit of logic in later calls so we don't need to get/lock/check the device if someone is spamming the consume endpoint.

> "get and lock all expired codes" -> shouldn't we actually be locking on device_id_hash?

We are locking the codes anyway since they are deleted in the next line. We could lock the related devices at the same time as well, but I'm not sure if that's necessary

**Comment by rishabhpoddar** [comment]
- [ ] We don't need the "delete all devices with more failedAttempts than configured max" since if the code is used later in the consume API, it will be deleted anyway. If it's never used again, it will expire and the cron will delete.

**Comment by rishabhpoddar** [comment]
# Draft Feecback
## https://app.code2flow.com/OFxcbh1FNLXd (POST /recipe/sigininup/code/consume)
- [ ] Line 45 can be broken down into two blocks.
- [ ] After line 45, If a device ID was passed, code exists, but it's expired, it should result in increasing the failed attempts count. This is not shown in the diagram.

**Comment by porcellus** [comment]
> After line 13, we need to check if the device has any code left. If not, we should delete the device.

Updated wording

**Comment by porcellus** [comment]
Diagram for single code remove: https://app.code2flow.com/DDhe9U1rsFsQ

**Comment by rishabhpoddar** [comment]
- [ ] We need to change the cronjob logic for removing the device ONLY when all of its codes have expired. This is so that in the consume API, we can distinguish between expired vs non existent codes.

**Comment by porcellus** [comment]
> We need to change the cronjob logic for removing the device ONLY when all of its codes have expired. This is so that in the consume API, we can distinguish between expired vs non existent codes.

I think you meant that we should only remove codes if all other codes have expired for the device - meaning that they are only removed when the device is cleaned up. I updated the chart accordingly

I also removed the "we should never get DuplicateEmailException" comment from the consume one, since it's no longer true.

**Comment by porcellus** [comment]
Since the implementation started I'll close this. Please refer to the code for the current version.
