### ISSUE TITLE
Cant set sAccessToken expiration to a year

### ISSUE THREAD

**Issue by frostbeer** [supertokens/supertokens-core#534]
## 🐛 Bug Report

Hey, i know it is not recommended but i tried setting the ACCESS_TOKEN_VALIDITY to 31536000 (1 year) but for some reason it created the access token with expiration of 17 days.
I also tried setting it 300 (5 minutes) and it worked correctly, expiration was 5 minutes.

I think there is some kind of limit on the type of ACCESS_TOKEN_VALIDITY.

One time i even tried setting it to 7890000 (3 months) and i think it gave me a an expiration in the past.

## Useful informations
Im using 
- supertokens/supertokens-postgresql docker image version 3.14
- supertokens golang sdk 0.9.7
- Gin web framework

Let me know if you want for additional information

**Comment by frostbeer** [comment]
Awesome thanks.

**Comment by rishabhpoddar** [comment]
This has been fixed in core version >= 4.2.1. If you are using self hosted, please clear the existing docker image you have and redownload the docker image of tag 4.2

If you are using our managed service, and the core version is 4.2, we will auto update this fix for you, else you can email us on team@supertokens.com and we will upgrade the core instance for you.
