### ISSUE TITLE
sIRTFrontend = sIdRefreshToken

### ISSUE THREAD

**Issue by hyperknot** [supertokens/supertokens-core#556]
## 🐛 Bug Report

After logging into the Next.js sample, sIRTFrontend = sIdRefreshToken in my case.

Isn't this a security problem, as sIdRefreshToken is HttpOnly, while sIRTFrontend is not?

I mean if we were not supposed to read sIdRefreshToken then we can do it now, because the same value is stored in a non-HttpOnly cookie as well.

## Useful informations

Next.js example, directly after logging in.

**Comment by hyperknot** [comment]
These 5 cookies are very confusing for me. Just by reloading the app many times I managed to get it to a state where it only has 3 cookies. (I used 10 second access token time).

<img width="149" alt="image" src="https://user-images.githubusercontent.com/494223/212446054-374db409-ad67-4a74-a4b6-17810b38695c.png">

Here the 2 cookies have the same content. 

If I refresh now, the app loads correctly, loads the 5 cookies.

=>

This way I can conclude that the content of the `sIdRefreshToken` is enough to bring up a full session. Which is not secure, as it's stored in an other cookie as well.

**Comment by hyperknot** [comment]
Just to confirm, out of the 5 cookies 1 is perfectly enough to recover the full session at startup: `sIdRefreshToken`.

And the contents of this cookie is mirrored in the non-HttpOnly `sIRTFrontend`.

**Comment by rishabhpoddar** [comment]
Hi.
So the cookies are as follows:
- sAccessToken: httpOnly access token that grants access to the APIs.
- sRefreshToken: httpOnly refresh token that is sent to the refresh API to get new session tokens.
- sIdRefreshToken: This is httpOnly token which is a random string that changes each time the refresh token changes. The value of this is not a secret. It's used during session verification to differentiate the case between try_refresh_token error vs unauthorised error in case the sAccessToken is missing in the request (cause it has expired)
- sFrontToken: This is just a token saved on the frontend. It is not a secret, but contains the access token payload that the user adds, so that it can be read on the frontend to perform authorization logic.
- sIRTFrontend: Used to determine if a session exists on the frontend + do synchronisation logic for refresh API calls. he value of this is just random and not a secret.

This being said, we are in the process of making things simpler by removing some tokens and renaming some of them to make it clear. But either way, this is not a security issue as of now cause all the sensitive tokens (sAccessToken and sRefreshToken are httpOnly).

**Comment by hyperknot** [comment]
Sorry, that is not the case. `sIRTFrontend` **is not random**. It is exactly the same as `sIdRefreshToken`. By knowing `sIRTFrontend` you have access to the full session!

That's what my bug report says, even the title. I don't understand why you closed it.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/494223/212469096-40d807ef-55c6-47d6-9de1-310656b22f01.png">

**Comment by rishabhpoddar** [comment]
`sIdRefreshToken` is random as well. It's **not** the refresh token. The refresh token is *sRefreshToken*.

**Comment by hyperknot** [comment]
If I remove all the cookies, except sIdRefreshToken, it gives me back into a full session (after reload).

From this:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/494223/212471126-f57253de-ffc0-4e15-83ab-f71d474130c1.png">

I get this:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/494223/212471137-40ae5963-9db0-47f4-aed5-427803815841.png">

**Comment by rishabhpoddar** [comment]
When you remove all the cookies, you must not be removing the sRefreshToken cookie (cause that is shown in the refresh API path and not all paths on chrome). So when you remove the other tokens (sAccessToken, sFrontToken, sIRTFrontend), then that triggers a refresh API call in which the sRefreshToken is sent to generate new tokens.

If you everything (including the sRefreshToken - which you will have to remove by navigating to the refresh API path on chrome), except for the sIdRefreshToken and then call an API or reload the page, it will result in you getting logged out.

**Comment by hyperknot** [comment]
I think I understand it's just Chrome which is not displaying the /api cookie, it's actually still there! I got it.
