### ISSUE TITLE
"Looks like something went wrong!"

### ISSUE THREAD

**Issue by kumkee** [supertokens/supertokens-core#593]
![image](https://user-images.githubusercontent.com/391431/227313289-859dc041-c1c0-481a-aaa4-30b77fde2519.png)

I got this error when trying to log on to `/auth/dashboard`
What could go wrong?

**Comment by rishabhpoddar** [comment]
I would need more info:
- Which backend SDK, backend SDK version and core version are you using? 
- Are you self hosting the core or using our managed service? 
   - If managed service, can you please email me (at rishabh@supertokens.com) from your registered email ID referencing this issue so that I can see what's wrong?
   - If self hosted, can you see the core's error log when this page is refreshed?
- Have you modified the contents of the SuperTokens' table in the db manually?
- Does login for your regular app work (for end users)?
- Do you see any error logs on the backend api layer process when loading this page?

**Comment by kumkee** [comment]
> I would need more info:
> 

My bad. I found out I got a mistake in my Core connectionURI in my backend code.

Hopefully, this mistake of mine will help someone debug in the future. 
I am closing the issue now.
