### ISSUE TITLE
Sanitization and escaping API in the core for login/signup

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-core#73]
## 🚀 Feature

The method would be called from the SDKs on signup, and maybe other functions too.

**Comment by rishabhpoddar** [comment]
Function signature:
```
sanatizeJson(inputJson): Promise<JSON>
```

**Comment by rishabhpoddar** [comment]
@NkxxkN how would this work? I have a few points below:
- For passwords and tokens, we do not want to sanitise them at all.
- For email:
   - Should this function assume that they are syntactically correct, since this function is called only after validators are called. If we do not assume that, then this function can throw errors as well, which needs to be accounted for in all the APIs. However, not checking for syntax correctness is a little strange IMO.
   - If the syntax is correct, then we can normalise the email. For example, `first.last@gmail.com` becomes `firstlast@gmail.com` since `gmail` does not distinguish between the two.. and there are many other such rules.
   - Should we also have escaping of characters here? I don't think so because if there are characters that need to be escaped, it probably means that the syntax of the email is incorrect?
- What all would generic sanitisation do?
- Are there any other special cases like email & password?
- Do we allow the user to tell us if should not escape a certain user input?

**Comment by NkxxkN** [comment]
First I think we need to make sure we understand the difference between escaping/sanitizing etc...

I borrowed the definitions from [security stack exchange](https://security.stackexchange.com/questions/143923/whats-the-difference-between-escaping-filtering-validating-and-sanitizing)
```
Escaping. Converting a control character to its escape sequence. For example, a < symbol may be converted to &lt; so that the characters following the < are not interpreted as an XML tag instead of XML content.

Filtering. Like escaping, but instead of replacing the control character, it is simply removed.

Validated. Comparison of an input against a white list or regular expression to detect control characters or other character sequences that would trigger an unauthorized behavior. For example, an account number entered by a user might be validated against a list of account numbers known to be tied to the user.

Sanitized. A combination of escaping, filtering, and validation that ensures that an input to a system function does not trigger an unexpected and unauthorized behavior.
```

> For passwords and tokens, we do not want to sanitise them at all.

👍 

> Should this function assume that they are syntactically correct, since this function is called only after validators are called.

I think our first idea in Notion doc was to call the sanitisation first, before the validators. 

> If the syntax is correct, then we can normalise the email.

I don't think we should modify the user email. If it complies to the RFC specifications of emails, then we should let them use it.
For example I often use the following format while registering `kevin+theproductname@...`. I wouldn't like if the company changed my email to `kevin@...`  as I wouldn't know about it and wouldn't be able to login. It actually happened couple of times and it was a bad experience. I think it's the same for "dots", most users don't even know when they signup with `first.name@` that they could get rid of the "dot", so it would lead to confusion.


Quick note on email:
Here are the email specifications as defined by the RFC standard: https://tools.ietf.org/html/rfc822
- They allow for . as you specified: `first.last@` is considered the same as `firstlast@`
- They allow for + `first+last@` is actually `first@` but that's a useful way of signing up multiple time to a product with the same email. 
- They allow for () `(comment)last@` or `first(comment)last@` , but this is not supported by most email services so I think it's safer to ignore.

> What all would generic sanitisation do?

For email:
 - filter for XSS injections
 - filter for SQL injections

Other fields:
 - filter for SQL injections
 - escape for XSS injections
 - validate against whitelist (if the users wants to, using our callbacks for input validation in the sdks).


I'm thinking that email validator should not be possible to override. Or at least, we should always run the default validation in addition to the user's provided one. Because we are going to be responsible for sending confirmation emails/ reset passwords etc... That way we never try to send emails to malformed emails.

Are there any other special cases like email & password?

I don't think there are in our case.

**Comment by rishabhpoddar** [comment]
> I think our first idea in Notion doc was to call the sanitisation first, before the validators.

By the stated definition of sanitisation, it includes validating. But here you say that we sanitise first, and then validate.

> as I wouldn't know about it and wouldn't be able to login

You would.. since your input email would go through the normalisation again.. So if you signed up with first.last@gmail.com, you can use that, or you can use firstlast@gmail.com to login. We do this for superotkens at the moment, and it works very well. I'm not sure if it converts `first+something@gmail.com` to `first@gmail.com`. @bhumilsarvaiya, what is the behaviour of our normalisation of email?

> Generic sanitisation for email

Wouldn't normalising and checking for syntax (using regex) fix the issue of filtering for XSS / SQL injection?

> I'm thinking that email validator should not be possible to override. Or at least, we should always run the default validation in addition to the user's provided one. Because we are going to be responsible for sending confirmation emails/ reset passwords etc... That way we never try to send emails to malformed emails.

We can have a check in our API for email as well.. if the syntax is incorrect, we throw a bad request error. I think they should have flexibility in their email validators and not be forced to use ours.

> That would be relevant if we were going to manage their whole product's API, but we are only responsible for login/signup. I don't see a case where you ask on registration to provide some html tags during user on-boarding.

Okay.

**Comment by NkxxkN** [comment]
> By the stated definition of sanitisation, it includes validating. But here you say that we sanitise first, and then validate.

Sorry it wasn't clear. The above definitions introduce a new concept of validation which is different from ours. It is about blacklisting/whitelisting only. When we talk about validators so far, it is validators defined by the end users (often business logic validators) which are not intended for security purposes necessarily.

I meant, sanitisation (escaping/filtering etc..) happens before validators defined by the user.

> Wouldn't normalising and checking for syntax (using regex) fix the issue of filtering for XSS / SQL injection?

Yes that should be enough indeed.

> We can have a check in our API for email as well.. if the syntax is incorrect, we throw a bad request error. I think they should have flexibility in their email validators and not be forced to use ours.

Makes sense!

**Comment by rishabhpoddar** [comment]
We are no longer doing this since:
- We will use prepared statements for SQL - prevents SQL injection
- We are not going to handle / store custom input fields sent by the user - this is their responsibility
- We are going to have email syntax checking in the SDK anyway.
