### ISSUE TITLE
Should we normalise emails in the default APIs on the backend?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#89]
## ❓ Questions and Help

@NkxxkN, in APIs and functions where the input is an email, should we normalise emails (AFTER running the validators) as per the `normalizeEmail` function in [this table](https://github.com/validatorjs/validator.js#sanitizers)?

-----------

## Edit:
We are only doing lower case for all emails

**Comment by NkxxkN** [comment]
You have a good point!

If we assume that our regex works, that would not be necessary.

But what if customers decide to override the email validator? They might miss some of the sanitisation?

Are you thinking of using this lib? Is that ok to use it as a dependency?

**Comment by rishabhpoddar** [comment]
> But what if customers decide to override the email validator? They might miss some of the sanitisation?

The normalise will run after the validator. So they can override the validator, in whichever way they want. 

> Are you thinking of using this lib? Is that ok to use it as a dependency?

Not sure. I want this type of normalisation to exist in the core and other SDKs as well. This lib is only for nodejs.. so maybe it's better if we implement our own or find something that can be easily ported to another framework.

Do you think it's a good idea to normalise email as per the rules of that function?

**Comment by NkxxkN** [comment]
That lib gives a lot of optional configs, we can decide to turn them on/off based on what we want.

For example there is an option to transform a+b@gmail.com into a@gmail.com, etc...
In that particular case, what it does really is that it prevents someone to signup multiple times with same email. Do we want to do that? It can be handy in some cases. I don't think we should decide for our customers.

Also it seems that some email providers have taken some liberties compared to the RFC standards. Yahoo considers that foo-bar@yahoo.com === foo@yahoo.com 

Wether we do it in the core or in SDKs, if we decide to actually normalize emails with those kind of method, we better use a lib than implementing on our own as it could result in some surprises since there seems to be some tricky edge cases.

**Comment by rishabhpoddar** [comment]
So we will need to do this in the Core, and in the SDK. For the default APIs that take email as an input, we need to normalise them at the start of the API. In case the user is not using our APIs and is using the functions we provide directly, then we too need to normalise the emails, but in the core. 

So what all will our email normaliser do?
- all_lowercase
- gmail_lowercase
- gmail_remove_dots
- gmail_convert_googlemaildotcom
- outlookdotcom_lowercase
- yahoo_lowercase
- icloud_lowercase

**Comment by NkxxkN** [comment]
- `all_lowercase` ✅  
  Includes `icloud_lowercase` `yahoo_lowercase` `outlookdotcom_lowercase` `gmail_lowercase`


`gmail_convert_googlemaildotcom` ? `Converts addresses with domain @googlemail.com to @gmail.com, as they're equivalent`, I can't see why this should be done. No opinion here.

`gmail_remove_dots` `gmail_remove_subaddress` `outlookdotcom_remove_subaddress` : As an end user, I don't like services doing that because that means I can't create multiple accounts with the same address. 

Will we sanitize for both signin/signup? What if new customers want to migrate to our service with their current db? that will cause outages if they don't have the same sanitization rules?

I think it's safe to do lowercases, but I'm not really comfortable with playing around with the emails rules depending on providers ... Seems like more complexity for no particular reason.

**Comment by rishabhpoddar** [comment]
Cool. I will only do lower case then.
